[package]
name = "rustproject"
version = "0.1.0"
edition = "2021"

[lib]
# name = "addlib"
name = "utillib"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
chrono = "0.4"